### ISSUE TITLE
[request] Colored Names

### ISSUE THREAD

**Issue by kreezxil** [sirdude/gurbalib#10]
Would like to have the option for colored player Names.

Looked all over the lib trying to find the best place to put it. Eventually created a new set of routines to do it. But then after a few reboots the mudlib started to act strange and it felt like it was forcing me to reverse all the places where I told the lib to use my new ```c query_colored_name()``` routine.

**Comment by sirdude** [comment]
This is complicated and I'm guessing what you want is in conflict with how colors are setup and used right now.  Colors are setup so that they are customizable by the user seeing the colors not the other way around.  If you type "ansi show" you can see colors you have and what they are defined for.  Players already have a color, which you can see in the look command, we could easily expand this to say who, score and other commands, however I'm guessing this would just make what you want more complicated not less. 

I think what you are requesting is being able to set my name so that say I could make my name RedGreen and have Red be read and Green be green for others.  This has a potential to be abused by players to make their name unreadable.  I understand the appeal of being able to make my name rainbow colored, it kind of goes against how the mudlib is setup though and would be very complicated to merge in with what is there right now.

I don't see me spending time on this anytime soon.  If you come up with something that integrates with the current system I'll consider adding it in but would probably want to discuss how it should work against the current system.

**Comment by sirdude** [comment]
I'm going to close this ticket but if someone decides to contribute a fix I'll accept it.

**Comment by shentino** [comment]
For the sake of future coders, I'd like to lay down a few caveats.

* How to encode?

Do you want ANSI color escapes?  Dead Souls style color tags?

Use the proper markup within the proper context.  Crat yelled at me once for sending raw ANSI escapes over intermud, so we want to avoid sending those over protocols that can't digest them.

* How to convert?

We need to distinguish the output formats, and also know how to convert between them and whatever format we use to store the colors natively.

* How to store?

A neutral markup language probably would be best.
