### ISSUE TITLE
rm_user doesn't work

### ISSUE THREAD

**Issue by evilmog** [sirdude/gurbalib#29]
rm_user errors out with

```
> rmuser mogtest
Removing mogtest, are you sure? (y/n)
y
Runtime error: Undefined function: remove_file
```

for some reason remove_file kfun doesn't seem to exist, I see it in the dgd source so I'm not sure whats up

**Comment by november-kilo** [comment]
The kfun is wrapped by `lib/kernel/lib/afun/remove_file.c`. It's static, which is why it can't be called from the user removal command. Looks like it should not be static (this came up over the summer, but went unresolved) so it can be called by `unguarded()` but I suppose there's a reason it's static. Not sure the solution off the top of my head.

**Comment by sirdude** [comment]
I removed the static call, might cause security issues which we can deal with moving forward but for now lets at least get it so the command works.
